### ISSUE TITLE
募集開始の号令の変更

### ISSUE THREAD

**Issue by showwin** [mikupaccho/gutto-paccho#14]
![screen shot 2018-03-07 at 12 00 49](https://user-images.githubusercontent.com/1732016/37071299-33d6c926-21ff-11e8-8240-f5a00de4651e.png)

の意味がわかりにくいので、
```
ランチ行く人〜 @here
```
とか初見でもわかるような内容にしてください！

**Comment by kahirokunn** [comment]
https://github.com/mikupaccho/gutto-paccho/pull/15
プルリクしました。
確認おねがいします。

**Comment by mikupaccho** [comment]
#16 #17 確認しました〜！！！
