### ISSUE TITLE
集計結果の出力をよくする

### ISSUE THREAD

**Issue by r-takahama** [mikupaccho/gutto-paccho#2]
見づらいので `@mikupaccho` にするとかそういういい感じにしましょう
<img width="394" alt="2018-02-23 14 22 57" src="https://user-images.githubusercontent.com/7949819/36579193-1d7aa4a8-18a5-11e8-8586-1e53161ff9ed.png">

**Comment by mikupaccho** [comment]
イシューの内容がわかりづらいです。が、直します。

**Comment by r-takahama** [comment]
いつのまにかなんか直ってました
