### ISSUE TITLE
カタカナの可愛さ指数のラベリング

### ISSUE THREAD

**Issue by r-takahama** [mikupaccho/gutto-paccho#21]
## 詳細
- 自動生成されるチーム名をかわいくする #13 を実装するにあたって必要
- 利用可能なカタカナの一覧について、適当な範囲の点数（たとえば0から100の整数など）を付与する

## 終了条件
- [x] 点数の範囲を決める -> 0から100の整数
- [x] 点数の保存方法を決める -> 暫定的に `data/char_scores.tsv` に置く
- [x] ラベリングを行う @mikupaccho

**Comment by graph226** [comment]
575じゃん

**Comment by r-takahama** [comment]
#a575 です

**Comment by r-takahama** [comment]
@mikupaccho ラベリングｵｱｼｬｰｽ! https://github.com/mikupaccho/gutto-paccho/edit/21/feature/char-labeling/data/char_scores.tsv

**Comment by r-takahama** [comment]
おわり！
