### ISSUE TITLE
botなどの `'user'` が存在しないアカウントが発話するとエラーが起こる

### ISSUE THREAD

**Issue by r-takahama** [mikupaccho/gutto-paccho#22]
## 詳細
<img width="838" alt="2018-03-08 20 47 45" src="https://user-images.githubusercontent.com/7949819/37149668-3692eb22-2312-11e8-88e4-3845f2d1d778.png">

- `'user'` の存在チェックを入れれば良さそう？

## 終了条件
- [x] botの発話に対してエラーを吐かなくなる

**Comment by denzow** [comment]
修正済なのでCloseします。
