### ISSUE TITLE
自然言語処理で、slack上で「行く」に近い単語でもチームに入れるようにする

### ISSUE THREAD

**Issue by yamad07** [mikupaccho/gutto-paccho#24]
## 詳細
- https://github.com/mikupaccho/gutto-paccho/commit/6e6a5b48c8c0ca5c7e46bc49ea10d04b9fc93189 現在、以下のように定義される `YES_MESSAGE_LIST` に含まれる要素に完全一致する応答を行った場合のみ、ユーザがbotに肯定的に反応したと解釈される
```python
YES_MESSAGE_LIST = ['はい', '行きます', 'おなかすいた']
```
- ユーザによっては、例えば「行きたい」などといったように、人間の目ではどうみても肯定的な反応であるが、リストとやや違うためにbotが正しく解釈できない場合が発生しうる
- word2vec等の自然言語処理技術を用いて、「行きます」に意味的に近い表現であるか否かを判断し、解釈できるようにしたい
- また、ユーザの意図と異なる解釈が行われてしまった場合にはそれを修正できるようにしたい

## 終了条件
- [x] 典型的な肯定的な反応、否定的な反応の例をいくつか用意する
- [ ] 上述した例を正しく分類できるようなアルゴリズムを実装する
- [ ] ユーザの意図と異なる解釈が行われてしまった場合にはそれを修正できるようになる

**Comment by dandersonw** [comment]
`str.contains('行') and not str.contains('かない')`

**Comment by r-takahama** [comment]
`行きません` に対して脆弱ではありませんか？

**Comment by r-takahama** [comment]
https://en.wikipedia.org/wiki/Word_embedding

**Comment by yutamaruyama28** [comment]
五段活用する日本語ってもしやめちゃ言語解析者泣かせな言語？

**Comment by yamad07** [comment]
アサインされた
word2vecで頑張るという手法でやってみますか

**Comment by r-takahama** [comment]
- Yesと判定されたものに `+:+1:` がつくのと同様、Noと判定されたものに `+:-1:` がつくと嬉しいです
- bot への新しい発話によって Yes, No を入れ替えられるようになるとさらに嬉しいです
- さらにさらに、募集中に参加表明以外の会話が発生する可能性があるので、どこかで閾値を切って `反応しない` パターンもあると嬉しいです
