### ISSUE TITLE
3チーム以上になる場合を考慮する

### ISSUE THREAD

**Issue by r-takahama** [mikupaccho/gutto-paccho#3]
現状だと100人が `はい` と答えた場合50人チームが2つになってしまうので、6人チームがたくさんできるようにする

**Comment by futai23** [comment]
1−8人:1チーム
9人-12人:2チーム
13-18人:3チーム
くらいが適切に思いますがいかがでしょうか？
 @r-takahama @mikupaccho @functionp

**Comment by r-takahama** [comment]
1チームMax6人でいいんじゃないでしょうか？

**Comment by futai23** [comment]
では、n // 6 チームの方針 にしましょう
@r-takahama

**Comment by r-takahama** [comment]
私がやりました #12
