### ISSUE TITLE
募集開始のときに分割人数を指定できるようにする

### ISSUE THREAD

**Issue by r-takahama** [mikupaccho/gutto-paccho#9]
## 詳細
- https://github.com/mikupaccho/gutto-paccho/commit/6e6a5b48c8c0ca5c7e46bc49ea10d04b9fc93189 現在、チームの最大人数はハードコーディングされて6人となっている
- 分割人数のデフォルト値が存在するのは構わないが、これは利用者側の要請によって柔軟に変更可能であるべきである
- 以上を踏まえ、募集開始の時に分割人数を指定できるようにする

## 終了条件
- [ ] 募集開始の時に分割人数を指定できるようになる
- [ ] [Optional, 別Issue?] デフォルトの分割人数を設定できるようになる

**Comment by denzow** [comment]
実装済
